### ISSUE TITLE
Array initialization

### ISSUE THREAD

**Issue by michaelsbradleyjr** [xTrayambak/librng#1]
https://github.com/xTrayambak/librng/blob/3b48d34e9984f8a479e918f636be304924f73ed3/src/librng/mersenne_twister.nim#L75-L79

Nim initializes `var state` for you, i.e. you don't need to supply an array literal with all zeros.

```nim
const NN = 312
var state: array[NN, uint64]
assert state[287] == 0'u64
```

Also, why do some of your modules use single-space indentation while others use the more common ("standard") two-space indentation?

**Comment by xTrayambak** [comment]
Hello there, I actually wrote the mersenne twister implementation in a hurry (it isn't even available yet, it just throws an error at runtime when you use it, intentionally). The indentation problem is due to the fact that I switched editors during the time I wrote this library. I'll fix all this tomorrow. Thanks for the heads-up!

**Comment by xTrayambak** [comment]
This is now fixed.
